### ISSUE TITLE
Mobile Gathering 1 uses move action

### ISSUE THREAD

**Issue by bje259** [Truinto/DarkCodex#10]
I was testing out some kineticist abilities and it seems that the first level of mobile gathering is coded as a movement action and my understanding is that it should be a free action to allow for the debuffed movement after using.  Unless, I'm misunderstanding, figured I would let you know! The second level coded as a standard action makes sense because that leaves your movement action still available and you would use a blast the next round.  I was testing with a demon kineticist so there's a chance something weird was going on there, but looking at the code is definitely looks coded as a move action.

Cheers!

**Comment by bje259** [comment]
Recompiling changing the .move to .free fixed what I think might be your intended design, but now I am trying to figure out why the movement debuff is only applying outside of combat, although my guess is that its either a mod conflict/override or related to some demonic rage affect that I don't know about.

**Comment by Truinto** [comment]
No, that's all intended. For real-time I needed to attach a slow, since that's the only way to reduce movement range (you can walk continuously unlike turn-based).
For turn-based I wrote a special function that refunds you half your movement speed. It uses a move action, but you can also walk half your speed. If you base speed is very low (dwarf, halfling, gnome), it might look like it's a 5 foot step, but it's not. Reason I code it that way, is that otherwise there are a lot of exploits.

Regarding the long version, I don't remember if I was finished with that. I think there was one minor exploit. I like never use it in my playthroughs anyway, since it's so bad skipping your whole turn.

Btw, mobile gather (short) has one little quirk. If you start combat with units overlapping, using the ability will cause you to move to a free spot.

**Comment by bje259** [comment]
That makes sense, I saw that contextactionundoaction code, but I wasn't noticing it in game. 

Cheers!

**Comment by bje259** [comment]
yes, I went back and confirmed its working as you described, I was just thrown off by the bars at the bottom.  thanks for all your work on the mod!
