### ISSUE TITLE
Scion focused element feature giving all composite blasts

### ISSUE THREAD

**Issue by Skiamach** [Truinto/DarkCodex#113]
Upon reaching 7th level my fire Elemental Scion gained all fire composite blasts (e.g., magma, steam, etc.). I thought I should have only gained the blue flame composite blast. Please note that I also have the Expanded Elements mod installed, which might be a factor. I am running version 1.3.24 of the mod.

**Comment by Mythalar** [comment]
Same thing here with air base element.
But I think it's a nice thing :p

**Comment by Truinto** [comment]
I replace the normal composite logic, since you cannot pick elements freely. Weird that that happens. I am sure I tested air.

**Comment by Mythalar** [comment]
With air only, at 7th I got blizzard, plasma, sandstorm, thunderstorms.
Actually I thought it was very cool and not so abusive since one does not qualify for wild talents/infusions that require the other base elements.
It allowed a wide variety of debuff, and builds that do not solely rely on ascended element (since one could change element on the fly, at the cost of the composite blast cost)

**Comment by Truinto** [comment]
Fix
