### ISSUE TITLE
Start the mod with no features on

### ISSUE THREAD

**Issue by trihardseven** [Truinto/DarkCodex#12]
I foolishly opened the game and turned everything off except feral combat training, which was the only thing I wanted from the mod, and went on to play normally for a few hours. Next day I couldn't load my save... 

Please make it more clear that you need to restart for things to register, and make it start with no features activated so this doesn't happen to someone else.

**Comment by Truinto** [comment]
There was a warning right above the settings. But I get the frustration. I am working on an overhaul of the settings anyway. Although it will take quite some work.

Note that most patches are not immediately required. I think the patches at might, all start with the suffix "create" and you need to pick the features in some way. Kineticist has a couple features which are granted automatically (selective metakinesis for example). Those you would need to remove with Toybox (or respec). One other big one is "Items.createKineticArtifact", it will add stuff to merchants. So that will probably be permanent.

**Comment by Truinto** [comment]
Improved behavior. It will now display a one time message on boot up, as well as pop-up after settings have been changed. I also marked which patches will definitely become a permanently requirement.
Let me know, if I missed to mark patches.
