### ISSUE TITLE
Massive mod manager log spam - appears to breaking all active abilities.

### ISSUE THREAD

**Issue by pheonix99** [Truinto/DarkCodex#19]
I have over ten thousand lines of nothing but:

[DarkCodex] Cast complete SacredArmorEnchantSwitchAbility from 

from a single five minute play session.

Note: I do not have a warpriest, and this continued while out of combat. As soon as this log spam starts, all abilities crap out - I can see the point where the spam starts and spells and abilities and even charge stop working quite clearly.

Please fix ASAP because this is literally gamebreaking.

**Comment by Truinto** [comment]
I have had this bug also. I am relatively sure it's not caused by my mod. During long play-sessions abilities would just stop working altogether. Only fix is saving and loading. Wasn't a big deal for me. I suppose the log messages are a result of the problem, not the problem itself. I just print this message to figure out when and which spells are being cast. It doesn't do anything by itself that could causes bugs.

If you find a way to easily reproduce the issue, I can look into it. Otherwise I don't know what to do.

**Comment by pheonix99** [comment]
I can reproduce it on my game whenever I do the Hand Of The Inheritor fight *however* have multiple custom mods installed.

Also I modded out the log-spam on my own dark codex compile and it didn't help.

I think it's whatever is spamming the toggle.

**Comment by Truinto** [comment]
The only thing that's related to warpriest is Mythic.createLimitlessWarpriest. And that's a tiny piece of code that just uses already existing features. No way that causes issues.

If it is an issue caused by a mod, then maybe I use that one too. I have Bubble Tweaks, Tabletop Tweaks, Dark Codex, and Toybox.

I think to remember that I also had this issue in that same fight. I ended up beating him up with just melee attacks. The game worked fine after that battle (after reloading). Maybe the combat initialization / cut scene causes the issue. Yeah, cut scene seems like a plausible component. But I am sure not every cut scene triggers the issue... This will be a tough bug to fix.

Do you have your game log still? I don't have a convenient save to try it out. Log is here: "%appdata%\..\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous"

**Comment by Truinto** [comment]
Can not confirm; did not get enough info.
