### ISSUE TITLE
Limitless Smite and Mark of Justice not limitless?

### ISSUE THREAD

**Issue by khoa0101** [Truinto/DarkCodex#229]
Hello,
I have the limitless Smite mythic ability. Prior to the latest update for the game, I also had limitless Mark of Justice due to this feat, now I'm limited to the normal amount of Mark of Justice, which is 7 at level 14. I test to see if this was a visual error, I used it on allies, and it in fact consumed the stack. Is that an intended change?
![image](https://user-images.githubusercontent.com/70730501/226153690-3b9b2dbb-3aee-4c5f-ab2b-1d7d04636647.png)

**Comment by Truinto** [comment]
7 uses are way too many for that level. That feature consumes 2 charges per use. Limitless smite reduces all uses by 1, which would fit your description.

You are probably looking for the option "Limitless feats always set cost to 0, instead of reducing by 1" in the mod menu (reallyFreeCost in the settings file).
