### ISSUE TITLE
Limitless Bardic Performance

### ISSUE THREAD

**Issue by rtam2166** [Truinto/DarkCodex#254]
Limitless Bardic Performance Mythic Ability makes bardic performances leave permanent buffs that last indefinitely and prevents the bard from switching to another bardic performance.

Testing Example:
Started a new game with a generic bard. After the opening was over, I used Toybox to add 9 levels and 1 mythic rank to the character. I then leveled bard up to level 3 to unlock "Inspire Competence" and used mythic rank 1 to unlock "Unlimited Bardic Performance". Then I activated "Inspire Courage", then tried to toggle "Inspire Courage" off and "Inspire Competence" on. The bardic performance did not change and the bard still had the "Inspire Courage" buff. 

I then used Toybox to remove the "Inspire Courage" buff which allowed me then to switch bardic performances.

Here are my game logs from the above test:
[GameLogFull.txt](https://github.com/Truinto/DarkCodex/files/11301910/GameLogFull.txt)
[GameLog.txt](https://github.com/Truinto/DarkCodex/files/11301914/GameLog.txt)

Here is a list of active mods:
Dark Codex 1.5.30
Respec Mod 1.10.14
Toybox 1.4.25

Love your mod, thanks for all the work you put into it.

**Comment by Truinto** [comment]
That's impossible. That feature only reduces the use cost to zero charges. It does not increase duration. And I have no other feature that would allow you to increase the duration either.

Did you wait a turn for the song to end? All activatables (toggle features) that aren't free actions (like bard songs) will last until end of turn, even if you turn them off. That's base game logic, not my doing. I know this, because it annoyed me too, when switching songs.

Thinking about this; I do have some other patches that could break with game updates. Would you please confirm that this is an issue?

**Comment by rtam2166** [comment]
I have retried my test above. Songs remain for well over 1 minute outside of combat and I have skipped several turns. In both cases, I have been unable to switch songs without manually removing the bardic song buff.

I was playing with your mod a couple weeks ago and did not notice this issue, so it is possible the most recent update broke this feature.

**Comment by Truinto** [comment]
Ah... I know what's happening. Someone asked for a more thorough infinite rage feature. Guess this applies to bard songs too. Wups.

**Comment by Truinto** [comment]
Thanks a lot for this report. It's fixed.

**Comment by rtam2166** [comment]
Thanks for the update. Happy to help.On Apr 23, 2023, at 11:39 AM, Truinto ***@***.***> wrote:﻿
Thanks a lot for this report. It's fixed.
