### ISSUE TITLE
A lot of Features of this mod don't work on the 1.2.0 Beta

### ISSUE THREAD

**Issue by Aberlolz** [Truinto/DarkCodex#29]
I wanted to prepare for the DLC with some new Character Ideas and noticed that a lot of things just are not there. All the Limitless Mythic Feats added by this mod are not there. I can't find Feral Combat Training in the normal Feats. The Kineticist Background seems to be missing aswell.

**Comment by Truinto** [comment]
I usually update when it's released. I like to avoid having to fix it more than once, in case there are major changes during development.
This means the latest version isn't immediately available. But GOG doesn't force updates, which is really nice. Steam is really annoying in that regard.

I would take a look at these future changes, but I couldn't find a beta channel for GOG users. Wouldn't be the first time Owlcat leaves GOG out of beta. So, if you find the beta channel password, I will look at it. Otherwise we are out of luck.

**Comment by Aberlolz** [comment]
As far as i know, the Beta is Steam only. Oh well, then i just write the Ideas down. not the World.
