### ISSUE TITLE
Feral Combat Training doesn't seem to work with Feral Mutagen claws

### ISSUE THREAD

**Issue by EnderWiggin** [Truinto/DarkCodex#35]
I have 3 attacks without feral mutagen (2 from BAB + 1 from Flurry of Blows). If I use mutagen and get claws + bite I get 2 attacks with main hand claw, 1 attack with secondary hand claw + 1 bite.  Is this correct amount of attacks? I assumed I would still get 3 attacks with main hand + secondary hand + bite. Am I wrong in this assumption?

**Comment by Truinto** [comment]
Flurry of Blows specifically says that it cannot be combined with natural attacks.
> A monk with natural weapons cannot use such weapons as part of a flurry of blows, nor can he make natural attacks in addition to his flurry of blows attacks.

High BAB does not apply to natural attacks, only weapons.
>You do not receive additional natural attacks for a high base attack bonus.

These should be your options:
- Claw, Claw, Bite
- Mainhand Sword (x2), Offhand Claw, Bite
- Fist (x3)

Also note that the game sometimes just forces you into some attack modes. For instance, you cannot choose to make an unarmed full-attack without also using Flurry of Blows.

I fail to see how this interacts with Feral Combat Training.

**Comment by EnderWiggin** [comment]
I experimented a bit and I think I've figured it out. I indeed loose al extra attacks due to BAB, but retain Flurry. So feral Mutagen is a tradeoff of having 1 less attack at max BAB, but all attacks are made at full BAB. And with Focussed Weapon training I can even have almost same damage dice progression as Monk fists.

**Comment by Truinto** [comment]
No idea how the game solves this. But on paper that means you can do the fist attacks with any natural attack instead. So 3x bite or claw. It does never grant extra attacks. I think that is in their FAQ.

**Comment by Truinto** [comment]
Here is the source:
https://paizo.com/paizo/faq/v5748nruor1g1#v5748eaic9ozd

Hope that answered your questions.

**Comment by aaronmaslen** [comment]
I think there's an issue with how the game decides on which attacks are used for flurry of blows: If I have a 1H monk weapon (sai) equipped and an empty (claw) off hand, I get 2+ (flurry+BAB) attacks with the main hand + 1 off hand (natural, secondary) attack + all other secondary natural attacks (bite, gore, etc.)

Feral Combat Training doesn't appear to affect this.

**Comment by Truinto** [comment]
I think most people have the misconception that Feral Combat Training allows them to get more attacks. It does not. The wording is very particular. It says "use natural weapons **with** your flurry of blows", not "use natural weapons **in addition to** your flurry of blows".

More clearly it should read:
> If you are a monk, you can use the selected natural weapon in your flurry of blows as if it were a manufactured monk weapon. You never gain any extra attacks per round because of this feat.

I looked at the game's blueprint. The base rules are not applied correctly. Specifically this one:
> A monk with natural weapons cannot use such weapons as part of a flurry of blows, nor can he make natural attacks in addition to his flurry of blows attacks.

You should not be allowed to use natural attacks. But the base game doesn't check for that. So it's screwed from the beginning. Feral Combat Training has indeed no effect on Flurry because of that.

I would need to change the following:
- Disable all natural attack, when a monk full-attacks
- If a monk has Feral Combat Training, is unarmed (no Monk weapon), repeatably use the most favorable natural attack or unarmed strike (whatever is better)
