### ISSUE TITLE
suggestion: dirty fighting

### ISSUE THREAD

**Issue by RevanStarforge** [Truinto/DarkCodex#82]
if it is not too much trouble, could you add this feat, since it would do wonders with animal companions

"Dirty Fighting (Combat)
You can take advantage of a distracted foe.

Benefit(s): When you attempt a combat maneuver check against a foe you are flanking, you can forgo the +2 bonus on your attack roll for flanking to instead have the combat maneuver not provoke an attack of opportunity. If you have a feat or ability that allows you to attempt the combat maneuver without provoking an attack of opportunity, you can instead increase the bonus on your attack roll for flanking to +4 for the combat maneuver check.

Special: This feat counts as having Dex 13, Int 13, Combat Expertise, and Improved Unarmed Strike for the purposes of meeting the prerequisites of the various improved combat maneuver feats, as well as feats that require those improved combat maneuver feats as prerequisites."

if memory serves, call of wild had this, and i think for simplicity sake it was on all the time, i don't want to patronize so i don't know how hard or easy to write this, but if proves problematic, i think you can check call of the wilds for kingmaker

**Comment by Truinto** [comment]
Small issue, the prerequisite for the greater maneuvers is not the feat, but the ability. Since you need the ability for this feat to make sense, you could pick the greater maneuvers.

Please let me know if the flanking boni work. I didn't come around to have time to test. You don't suffer an attack of opportunity but incure a -4 penalty if you are not flanking and don't have the right maneuver feat.
