### ISSUE TITLE
Blood Kineticist Fix

### ISSUE THREAD

**Issue by Truinto** [Truinto/DarkCodex#88]
### Discussed in https://github.com/Truinto/DarkCodex/discussions/84

<div type='discussions-op-text'>

<sup>Originally posted by **mccabefliam** July  6, 2022</sup>
Was wondering if you could tackle the bugged archetype that's been useless since game has been in our hands. Wrack not always doing the correct damage and the bleed infusion only ever applying 1 bleed at a time instead of 1 bleed per a damage dice. Minor bugs being the blood blast being called charged water blast (while still only doing physical i believe). 

A fix to this would be super appreciated. </div>

**Comment by Truinto** [comment]
I made a couple fixes, but not sure how good they are. Did not touch Wrack, that bug description doesn't help me. Please provide feedback.

**Comment by Mythalar** [comment]
So I ran a fex tests (challenging, so no issue with difficulty settings this time !)

- Water + wrack -> no issue (half damage, quater if save)
- Blood + wrack -> does full bludgeoning damage (composite) instead of half untyped / quarter if save (but does not require touch attack rolls, that at least is right)
- Bleeding -> new debuff correctly applied (since it's in english whereas my game is in french), but does not deal any damage (tested from beginning to level 12), no occurence of bleed in the logs at all
- Blood composite infusion still mostly refers to the charged water blast tooltips (eletric damage etc...)
- Vampiric infusion : cannot really test since kinetic healer was already at 0 cost at level 12, I guess the class reduction to costs also apply to wild talents, same with grease wild talent (it should not I think), but I think the infusion is wrong : it should not be a cost reduction but it should allow the kineticist to use it as a free action [Vampiric infusion](https://www.d20pfsrd.com/alternative-rule-systems/occult-adventures/occult-classes/kineticist/archetypes/paizo-llc-kineticist-archetypes/blood-kineticist-kineticist-archetype/#Vampiric_Infusion_Su)

**Comment by Truinto** [comment]
Okay, I fixed a bug in my bleed logic. And also rewrote the vampiric infusion. I did not test it. Please test, pretty please.

**Comment by Truinto** [comment]
About blood + wrack. If your blast does at least twice as much damage as the enemy has DR, then it really doesn't matter.
Example: damage = 50, DR = 20
- all one type: 20 damage is resisted, 30 damage is dealt
- split type: 20 physical damage is resisted, 5 physical damage and 25 untyped damage is dealt

I will need to remember to check the strings again.

**Comment by Mythalar** [comment]
So vampiric infusion seems to work as you described since it activates on my character each time i use my vampiric blast.

Now bleed damages are there but always =1 and not the numbe of dices of the used blast.

Regarding blood+wrack I don't really agree with you since wrack should, at best, does half the composite blast damage (quarter if save), but it actually does full composite damage. Perhaps I was not very clear myself (the damage type was only part of the bug).

Exemple : Blood is a physical composite blast, with only bludgeoning damage so 2D6+2+CON mod (+2D6+2 / 2 levels)
So at level 6 : 12D6 +12 + CON mod
Wrack infusion does only half damage, quarter on succesful fort save so one should deal (12D6+12+CON) / 2
As of now it's full blast damage (and no Fort check at all)

Your point stands toward DR, but only if there is no enemy fully immuned to this specific damage type.

**Comment by Truinto** [comment]
Continues at #121
